//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CR2W.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CResourceExt {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CResourceExt() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CR2W.Resources.CResourceExt", typeof(CResourceExt).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redcsv.
        /// </summary>
        public static string C2dArray {
            get {
                return ResourceManager.GetString("C2dArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redcloth.
        /// </summary>
        public static string CApexClothResource {
            get {
                return ResourceManager.GetString("CApexClothResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redapex.
        /// </summary>
        public static string CApexDestructionResource {
            get {
                return ResourceManager.GetString("CApexDestructionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2am.
        /// </summary>
        public static string CAreaMapPinsResource {
            get {
                return ResourceManager.GetString("CAreaMapPinsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2beh.
        /// </summary>
        public static string CBehaviorGraph {
            get {
                return ResourceManager.GetString("CBehaviorGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2behtree.
        /// </summary>
        public static string CBehTree {
            get {
                return ResourceManager.GetString("CBehTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xbm.
        /// </summary>
        public static string CBitmapTexture {
            get {
                return ResourceManager.GetString("CBitmapTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2cent.
        /// </summary>
        public static string CCharacterEntityTemplate {
            get {
                return ResourceManager.GetString("CCharacterEntityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2comm.
        /// </summary>
        public static string CCommunity {
            get {
                return ResourceManager.GetString("CCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redexp.
        /// </summary>
        public static string CCookedExplorations {
            get {
                return ResourceManager.GetString("CCookedExplorations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2cube.
        /// </summary>
        public static string CCubeTexture {
            get {
                return ResourceManager.GetString("CCubeTexture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2cutscene.
        /// </summary>
        public static string CCutsceneTemplate {
            get {
                return ResourceManager.GetString("CCutsceneTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reddlc.
        /// </summary>
        public static string CDLCDefinition {
            get {
                return ResourceManager.GetString("CDLCDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w3dyng.
        /// </summary>
        public static string CDyngResource {
            get {
                return ResourceManager.GetString("CDyngResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w3app.
        /// </summary>
        public static string CEntityExternalAppearance {
            get {
                return ResourceManager.GetString("CEntityExternalAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2em.
        /// </summary>
        public static string CEntityMapPinsResource {
            get {
                return ResourceManager.GetString("CEntityMapPinsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2ent.
        /// </summary>
        public static string CEntityTemplate {
            get {
                return ResourceManager.GetString("CEntityTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to env.
        /// </summary>
        public static string CEnvironmentDefinition {
            get {
                return ResourceManager.GetString("CEnvironmentDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2animev.
        /// </summary>
        public static string CExtAnimEventsFile {
            get {
                return ResourceManager.GetString("CExtAnimEventsFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to flyr.
        /// </summary>
        public static string CFoliageResource {
            get {
                return ResourceManager.GetString("CFoliageResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2fnt.
        /// </summary>
        public static string CFont {
            get {
                return ResourceManager.GetString("CFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to formation.
        /// </summary>
        public static string CFormation {
            get {
                return ResourceManager.GetString("CFormation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redfur.
        /// </summary>
        public static string CFurMeshResource {
            get {
                return ResourceManager.GetString("CFurMeshResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2w.
        /// </summary>
        public static string CGameWorld {
            get {
                return ResourceManager.GetString("CGameWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to grassmask.
        /// </summary>
        public static string CGenericGrassMask {
            get {
                return ResourceManager.GetString("CGenericGrassMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to guiconfig.
        /// </summary>
        public static string CGuiConfigResource {
            get {
                return ResourceManager.GetString("CGuiConfigResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hud.
        /// </summary>
        public static string CHudResource {
            get {
                return ResourceManager.GetString("CHudResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redicsv.
        /// </summary>
        public static string CIndexed2dArray {
            get {
                return ResourceManager.GetString("CIndexed2dArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2job.
        /// </summary>
        public static string CJobTree {
            get {
                return ResourceManager.GetString("CJobTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2je.
        /// </summary>
        public static string CJournalInitialEntriesResource {
            get {
                return ResourceManager.GetString("CJournalInitialEntriesResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to journal.
        /// </summary>
        public static string CJournalResource {
            get {
                return ResourceManager.GetString("CJournalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2l.
        /// </summary>
        public static string CLayer {
            get {
                return ResourceManager.GetString("CLayer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2mg.
        /// </summary>
        public static string CMaterialGraph {
            get {
                return ResourceManager.GetString("CMaterialGraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2mi.
        /// </summary>
        public static string CMaterialInstance {
            get {
                return ResourceManager.GetString("CMaterialInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        public static string CMenuResource {
            get {
                return ResourceManager.GetString("CMenuResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2mesh.
        /// </summary>
        public static string CMesh {
            get {
                return ResourceManager.GetString("CMesh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w3fac.
        /// </summary>
        public static string CMimicFace {
            get {
                return ResourceManager.GetString("CMimicFace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2steer.
        /// </summary>
        public static string CMoveSteeringBehavior {
            get {
                return ResourceManager.GetString("CMoveSteeringBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2p.
        /// </summary>
        public static string CParticleSystem {
            get {
                return ResourceManager.GetString("CParticleSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to reddest.
        /// </summary>
        public static string CPhysicsDestructionResource {
            get {
                return ResourceManager.GetString("CPhysicsDestructionResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to popup.
        /// </summary>
        public static string CPopupResource {
            get {
                return ResourceManager.GetString("CPopupResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2quest.
        /// </summary>
        public static string CQuest {
            get {
                return ResourceManager.GetString("CQuest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2qm.
        /// </summary>
        public static string CQuestMapPinsResource {
            get {
                return ResourceManager.GetString("CQuestMapPinsResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2phase.
        /// </summary>
        public static string CQuestPhase {
            get {
                return ResourceManager.GetString("CQuestPhase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2ragdoll.
        /// </summary>
        public static string CRagdoll {
            get {
                return ResourceManager.GetString("CRagdoll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w3simplex.
        /// </summary>
        public static string CResourceSimplexTree {
            get {
                return ResourceManager.GetString("CResourceSimplexTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2anims.
        /// </summary>
        public static string CSkeletalAnimationSet {
            get {
                return ResourceManager.GetString("CSkeletalAnimationSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2rig.
        /// </summary>
        public static string CSkeleton {
            get {
                return ResourceManager.GetString("CSkeleton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spawntree.
        /// </summary>
        public static string CSpawnTree {
            get {
                return ResourceManager.GetString("CSpawnTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2scene.
        /// </summary>
        public static string CStoryScene {
            get {
                return ResourceManager.GetString("CStoryScene", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2dset.
        /// </summary>
        public static string CStorySceneDialogset {
            get {
                return ResourceManager.GetString("CStorySceneDialogset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cellmap.
        /// </summary>
        public static string CSwarmCellMap {
            get {
                return ResourceManager.GetString("CSwarmCellMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redswf.
        /// </summary>
        public static string CSwfResource {
            get {
                return ResourceManager.GetString("CSwfResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2sf.
        /// </summary>
        public static string CSwitchableFoliageResource {
            get {
                return ResourceManager.GetString("CSwitchableFoliageResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w2ter.
        /// </summary>
        public static string CTerrainTile {
            get {
                return ResourceManager.GetString("CTerrainTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to texarray.
        /// </summary>
        public static string CTextureArray {
            get {
                return ResourceManager.GetString("CTextureArray", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to w3occlusion.
        /// </summary>
        public static string CUmbraTile {
            get {
                return ResourceManager.GetString("CUmbraTile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vbrush.
        /// </summary>
        public static string CVegetationBrush {
            get {
                return ResourceManager.GetString("CVegetationBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redwpset.
        /// </summary>
        public static string CWayPointsCollectionsSet {
            get {
                return ResourceManager.GetString("CWayPointsCollectionsSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to redgame.
        /// </summary>
        public static string CWitcherGameResource {
            get {
                return ResourceManager.GetString("CWitcherGameResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to wizdef.
        /// </summary>
        public static string CWizardDefinition {
            get {
                return ResourceManager.GetString("CWizardDefinition", resourceCulture);
            }
        }
    }
}
