using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using CR2W.IO;

namespace CR2WConsole
{
    public static class WriterTesting
    {
        public static void Test()
        {
            var mem = new MemoryStream();
            var bw = new CR2WBinaryWriter(mem);

            #region Values: r4defult.guiconfig
            bw.AddName("CGuiConfigResource");
            bw.AddName("huds");
            bw.AddName("array:2,0,SHudDescription");
            bw.AddName("hudName");
            bw.AddName("CName");
            bw.AddName("DefaultHud");
            bw.AddName("hudResource");
            bw.AddName("soft:CHudResource");
            bw.AddResource("CHudResource", "gameplay\\gui_new\\guirsrc\\default.hud", 4);
            bw.AddName("menus");
            bw.AddName("array:2,0,SMenuDescription");
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("InventoryMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4inventory.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MapMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4map.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MenuBase");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4menubase.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MeditationClockMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4meditation_clock.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CharacterMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4character.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("NoticeBoardMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4noticeboard.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("AlchemyMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4alchemy.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CraftingMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4crafting.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CommonMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4common.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CharacterSkillsMenu");
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("JournalQuestMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4journalquest.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("RescaleMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4uirescale.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("TestMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4test.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("EndScreenMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4endscreenmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("StartScreenMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4startscreenmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CommonMainMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4commonmainmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MainNewGameMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4mainnewgame.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("StartupMoviesMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4startupmovies.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("IngameMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4ingamemenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CommonIngameMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4ingamecommonmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MainGammaMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4maingamma.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("PopupMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4popup.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("LoadingMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4loading.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryBestiaryMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary_bestiary.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryTutorialsMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary_tutorials.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("PopupGlobal");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4popup.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("SelectItemMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4selectitem.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("PosterMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4poster.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("BlacksmithMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4blacksmith.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("MainDbgStartQuestMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4maindbgstartquest.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("DeckBuilder");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4deck_builder.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GwintGame");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4gwint_game.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryEncyclopediaMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary_encyclopedia.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryStorybookMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary_storybook.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("AutosaveWarningMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4autosave_warning_menu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CreditsMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4creditsmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("RecapMoviesMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4recapmovies.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("DeathScreenMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4deathscreenmenu.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("EnchantingMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4enchanting.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CommonMainMenuEP1");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4commonmainmenuep1.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("StartScreenMenuEP1");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4startscreenmenuep1.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("GlossaryBooksMenu");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4glossary_books.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("StartScreenMenuEP2");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4startscreenmenuep2.menu", 4);
            bw.AddName("menuName");
            bw.AddName("CName");
            bw.AddName("CommonMainMenuEP2");
            bw.AddName("menuResource");
            bw.AddName("soft:CMenuResource");
            bw.AddResource("CMenuResource", "gameplay\\gui_new\\guirsrc\\r4commonmainmenuep2.menu", 4);
            bw.AddName("popups");
            bw.AddName("array:2,0,SPopupDescription");
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("TestPopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4testpopup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("Test2Popup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4test2popup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("TutorialPopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4tutorialpopup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("MessagePopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4messagepopup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("OverlayPopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4overlaypopup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("LootPopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4lootpopup.popup", 4);
            bw.AddName("popupName");
            bw.AddName("CName");
            bw.AddName("ItemSelectionPopup");
            bw.AddName("popupResource");
            bw.AddName("soft:CPopupResource");
            bw.AddResource("CPopupResource", "gameplay\\gui_new\\guirsrc\\r4itemselectionpopup.popup", 4);
            bw.AddName("scene");
            bw.AddName("SGuiSceneDescription");
            bw.AddName("enabled");
            bw.AddName("Bool");
            #endregion

            bw.WriteAll();

            using (var br = new CR2WTestReader(mem.ToArray(), Console.Out))
            {
                br.ReadAll();
            }

            bw.Dispose();
            mem.Dispose();
        }
    }
}
